# Generated by Django 4.2.1 on 2024-02-11 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="carbohydrates",
            new_name="carbohydrate",
        ),
    ]
